# Generated by Django 5.1.1 on 2024-10-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('nome', models.CharField(max_length=255)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('carga_horaria', models.IntegerField()),
                ('requisitos', models.TextField()),
                ('modalidade', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=200)),
            ],
        ),
    ]
