# Generated by Django 5.1.1 on 2024-10-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totemapp', '0002_alter_curso_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='programacao',
            field=models.TextField(default=''),
        ),
    ]
