# Generated by Django 5.0.7 on 2024-10-10 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totemapp', '0003_curso_programacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='grade',
        ),
    ]
