# Generated by Django 5.0.7 on 2024-10-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totemapp', '0004_remove_curso_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='desc',
            field=models.CharField(max_length=1000),
        ),
    ]
