# Generated by Django 5.0.7 on 2024-10-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totemapp', '0007_interessado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interessado',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='interessado',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='interessado',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
