# Generated by Django 5.0.7 on 2024-10-22 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totemapp', '0010_interesse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interesse',
        ),
    ]
