# Generated by Django 5.0.7 on 2024-10-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totemapp', '0012_interesse'),
    ]

    operations = [
        migrations.AddField(
            model_name='interesse',
            name='curso_nome',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
