# Generated by Django 5.0.7 on 2024-10-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totemapp', '0013_interesse_curso_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='gratis',
            field=models.BooleanField(default=False, verbose_name='Gratuito?'),
        ),
        migrations.AddField(
            model_name='curso',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
