# Generated by Django 5.0.7 on 2024-10-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totemapp', '0014_curso_gratis_curso_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='valor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
