# Generated by Django 5.0.7 on 2024-11-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totemapp', '0016_alter_curso_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='gratis',
            field=models.BooleanField(default=True, verbose_name='Gratuito?'),
        ),
        migrations.AlterField(
            model_name='interesse',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='interesse',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
